{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/r50/core-r50.module",
    "group": "bruhcollective.itaysonlab.ksteam",
    "module": "core",
    "version": "r50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "bruhcollective.itaysonlab",
          "module": "kotlinx-vdf",
          "version": {
            "requires": "r50"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "bruhcollective.itaysonlab.ksteam",
          "module": "proto-common",
          "version": {
            "requires": "r50"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "5.5.1"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-grpc-client",
          "version": {
            "requires": "5.5.1"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-jvm-r50.jar",
          "url": "core-jvm-r50.jar",
          "size": 445735,
          "sha512": "e92c9e6d3d23c269ddb6e19916ae827d49336a855bec5a523d38b1052557c6731deaf1730c3783c56ed60d32ff0cd9e2fff635140e88e37d777eb74166a78d1d",
          "sha256": "5fd9dedfd686f97544f43bde94557c8e69eb2a95c26d508c87bd78d7d5078c56",
          "sha1": "db5f3b803df8370a2c4aed43af6b3a2a78e9ce7f",
          "md5": "3ee855e34733de3be8d807aa7f75d23d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "bruhcollective.itaysonlab",
          "module": "kotlinx-vdf",
          "version": {
            "requires": "r50"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "bruhcollective.itaysonlab.ksteam",
          "module": "proto-common",
          "version": {
            "requires": "r50"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "5.5.1"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-grpc-client",
          "version": {
            "requires": "5.5.1"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.4.2"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.2"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.4.2"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.4.2"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.2"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.2"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.4.0"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-okio",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.17.0"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-jvm-r50.jar",
          "url": "core-jvm-r50.jar",
          "size": 445735,
          "sha512": "e92c9e6d3d23c269ddb6e19916ae827d49336a855bec5a523d38b1052557c6731deaf1730c3783c56ed60d32ff0cd9e2fff635140e88e37d777eb74166a78d1d",
          "sha256": "5fd9dedfd686f97544f43bde94557c8e69eb2a95c26d508c87bd78d7d5078c56",
          "sha1": "db5f3b803df8370a2c4aed43af6b3a2a78e9ce7f",
          "md5": "3ee855e34733de3be8d807aa7f75d23d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-r50-sources.jar",
          "url": "core-jvm-r50-sources.jar",
          "size": 81990,
          "sha512": "a19846a5caad60f2968f611ccb4d42cfbcd73af118b365b28a5379a3ea356ddd0d21979763724deecd2a8b22408cf47b971edd2decd620c9ca696de4b0db2c69",
          "sha256": "b41a5e604bf349d0bfa213e76635bb4cf4a4f28a61ef07de91b7746c17c2752f",
          "sha1": "3330873309985ac5175eec8045b099e10a3be656",
          "md5": "a79ed7eaf1c0a4f437ddc2952ca660e5"
        }
      ]
    }
  ]
}
