{
  "formatVersion": "1.1",
  "component": {
    "url": "../../proto-common/r50/proto-common-r50.module",
    "group": "bruhcollective.itaysonlab.ksteam",
    "module": "proto-common",
    "version": "r50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-grpc-client",
          "version": {
            "requires": "5.5.1"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "5.5.1"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "proto-common-jvm-r50.jar",
          "url": "proto-common-jvm-r50.jar",
          "size": 22511586,
          "sha512": "b79592d688e63418de4baf8df4d2089f2c18bc74ca987a430637120e154bd6814a6586ba15b335aff7e9c187c2613ed234c2fa9fab16ab3141ebff7e7958f077",
          "sha256": "41b19e962413a8920f029198e6c920e07f65df1d7405914e9858dd9b4db73a17",
          "sha1": "94b5f3f7ac148838198232d20ac66ff7c5b7c450",
          "md5": "0cdb65f9d8d0a0410ea2ff77452514c6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-grpc-client",
          "version": {
            "requires": "5.5.1"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "5.5.1"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "proto-common-jvm-r50.jar",
          "url": "proto-common-jvm-r50.jar",
          "size": 22511586,
          "sha512": "b79592d688e63418de4baf8df4d2089f2c18bc74ca987a430637120e154bd6814a6586ba15b335aff7e9c187c2613ed234c2fa9fab16ab3141ebff7e7958f077",
          "sha256": "41b19e962413a8920f029198e6c920e07f65df1d7405914e9858dd9b4db73a17",
          "sha1": "94b5f3f7ac148838198232d20ac66ff7c5b7c450",
          "md5": "0cdb65f9d8d0a0410ea2ff77452514c6"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "proto-common-jvm-r50-sources.jar",
          "url": "proto-common-jvm-r50-sources.jar",
          "size": 5922729,
          "sha512": "5610b9efdb3860dd0357decf3efa18505d79397e3a4e57831a814c97d1bfcaaeba94a0f5b2b76d978447cb67ec244d2984986dd5f0396c452471447e71be3bb4",
          "sha256": "2617e8c78c68160c0e72831b51bc59e745c8141d93b7f014694d78527e183cf9",
          "sha1": "7ff3478881a79ad3afd1b0105c1ab96eb0ad9f00",
          "md5": "4fd0d302bca839569df57b63c251ebe9"
        }
      ]
    }
  ]
}
