{
  "formatVersion": "1.1",
  "component": {
    "group": "bruhcollective.itaysonlab.ksteam",
    "module": "core-persistence",
    "version": "r50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "bruhcollective.itaysonlab.ksteam",
          "module": "core",
          "version": {
            "requires": "r50"
          }
        },
        {
          "group": "bruhcollective.itaysonlab.ksteam",
          "module": "proto-common",
          "version": {
            "requires": "r50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-persistence-metadata-r50.jar",
          "url": "core-persistence-r50.jar",
          "size": 755,
          "sha512": "2ae887a7711f11c24be1ff3d25e982648315b443ef402b8da8a0b2f571275c3f152dfb19d76eef5fa84da710cd6416d03dc0ae4ef8f77a5681404e64bee81c86",
          "sha256": "395a8a8d9353ac044f7cf6fbf8aab066f43803de01e37f273976741c49bfe6fd",
          "sha1": "1812bd9cc4f4e72d76ed04bea928ada33b2d65e1",
          "md5": "582d0e867c618ce56d37b53c0c3c491b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-persistence-kotlin-r50-sources.jar",
          "url": "core-persistence-r50-sources.jar",
          "size": 2211,
          "sha512": "d87952351f1f3d182f79799f7a1463f7e1dd990d2b107a8b79e024cd0136464e9fe57a453fa98f65b322878b93222afb94cda3dc8b340467b8cec63a524a0b49",
          "sha256": "2e31c8d36ab09cf9dfe94f59bf1d38937f1b9ad6eaff972ccffc4601ecc75a58",
          "sha1": "3ea8fee375d301ba54735f4d64b000c4fef2c810",
          "md5": "9df6dce8fc912290fbc55d869aa04147"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-persistence-android/r50/core-persistence-android-r50.module",
        "group": "bruhcollective.itaysonlab.ksteam",
        "module": "core-persistence-android",
        "version": "r50"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-persistence-android/r50/core-persistence-android-r50.module",
        "group": "bruhcollective.itaysonlab.ksteam",
        "module": "core-persistence-android",
        "version": "r50"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-persistence-android/r50/core-persistence-android-r50.module",
        "group": "bruhcollective.itaysonlab.ksteam",
        "module": "core-persistence-android",
        "version": "r50"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-persistence-jvm/r50/core-persistence-jvm-r50.module",
        "group": "bruhcollective.itaysonlab.ksteam",
        "module": "core-persistence-jvm",
        "version": "r50"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-persistence-jvm/r50/core-persistence-jvm-r50.module",
        "group": "bruhcollective.itaysonlab.ksteam",
        "module": "core-persistence-jvm",
        "version": "r50"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-persistence-jvm/r50/core-persistence-jvm-r50.module",
        "group": "bruhcollective.itaysonlab.ksteam",
        "module": "core-persistence-jvm",
        "version": "r50"
      }
    }
  ]
}
